version: 1.0.{build}
configuration: Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: Iomgjn0cFHS8qYnmbZMtbaC3H68LMFwuOi9iJE5WH84lUeWgoq9gPcIu5cVRvZIF
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(assembly_version)
  assembly_file_version: $(assembly_version)
  assembly_informational_version: $(assembly_informational_version)
install:
- ps: >-
    dotnet --info
build_script:
- ps: .\build.ps1 -Target Appveyor
artifacts:
- path: .\artifacts\*.nupkg
- path: .\coverage-results\*
deploy:
- provider: NuGet
  api_key:
    secure: EMoHTW3rc1OUCEnrICn6gxCbaT8a3HSkedN6mbHqOzo1KHQodR13frz6FZwQuweE
  on:
    APPVEYOR_REPO_TAG: true
